{% set name = "qtspell" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/manisandro/qtspell/archive/refs/tags/{{ version }}.tar.gz
  sha256: 03bb9ef504dff352e162b91e9da89fb34d236e01da54799db69388dc9ceea4c2

build:
  number: 1
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('qtspell', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - pkg-config
    - doxygen
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - qt-main
    - enchant
  run:
    - qt-main
    - enchant

test:
  commands:
    - test -f $PREFIX/lib/libqtspell-qt5.so

about:
  home: https://github.com/manisandro/qtspell
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  summary: Spell checking for Qt text widgets

extra:
  recipe-maintainers:
    - izahn
